<a href="https://colab.research.google.com/github/abohashem95/SKlearn-codes/blob/main/Data_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Scaling 

## StandardScaler  (Standardization)



y = (x – mean) / standard_deviation

Where the mean is calculated as:

mean = sum(x) / count(x)

And the standard_deviation is calculated as:

standard_deviation = sqrt( sum( (x – mean)^2 ) / count(x))





In [ ]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
scaler.fit(data)
print(scaler.mean_)
newdata = scaler.transform(data)
print(newdata)

[0.5 0.5]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


In [ ]:
# or 

newdata = scaler.fit_transform(data) 
print(newdata)

[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


using in train and test data

just example without data

sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)

X_test = sc_X.transform(X_test)

sc_y = StandardScaler()

y_train = sc_y.fit_transform(y_train)

y_test = sc_y.fit_transform(y_test)


## MinMaxScaler (Normalization)


y = (x – min) / (max – min)

Where the minimum and maximum values pertain to the value x being normalized


In [ ]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler()
scaler.fit(data)
print(scaler.data_range_)
print(scaler.data_min_)
print(scaler.data_max_)
newdata = scaler.transform(data)
print(newdata)

[ 2. 16.]
[-1.  2.]
[ 1. 18.]
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


## Normalizer

و هي مخصصة لتناول كل صف علي حدة في المصفوفات ثنائية الأبعاد

In [ ]:
from sklearn.preprocessing import Normalizer
X = [[4, 1, 2, 2], [1, 3, 9, 3], [5, 7, 5, 1]]
# تستخدم l1  لجعل مجموع كل صف هو القيمة العظمي 
#transformer = Normalizer(norm='l1' )
# تستخدم l2 لجعل جذر مجموع مربعات كل صف هو القيمة العظمي 
#transformer = Normalizer(norm='l2' )
# تستخدم max   لجعل القيمة العظمي في كل صف هي القيمة العظمي
transformer = Normalizer(norm='max' )

transformer.fit(X)
transformer.transform(X)

array([[1.        , 0.25      , 0.5       , 0.5       ],
       [0.11111111, 0.33333333, 1.        , 0.33333333],
       [0.71428571, 1.        , 0.71428571, 0.14285714]])

## MaxAbsScaler
مشابهة لـ normalizer

لكن بالنسبة للعمود و ليس الصف حيث تجعل أكبر قيمة في كل عمود هي القيمة 


العظمي و تغير الباقيين علي اساسه

In [ ]:
from sklearn.preprocessing import MaxAbsScaler
X = [[ 1., 10., 2.],
     [ 2., 0., 0.],
     [ 5., 1., -1.]]
transformer = MaxAbsScaler().fit(X)
transformer
transformer.transform(X)

array([[ 0.2,  1. ,  1. ],
       [ 0.4,  0. ,  0. ],
       [ 1. ,  0.1, -0.5]])

## FunctionTransformer

وهي تستخدم لعمل سكيل بدالة اقوم كتابتها بنفسي


FunctionTransformer(func=None, inverse_func=None, validate= None,
                    accept_sparse=False,pass_y='deprecated', check_inverse=True,
                    kw_args=None,inv_kw_args=None)

In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

X = [[4, 1, 2, 2], [1, 3, 9, 3], [5, 7, 5, 1]]

def function1(z):
    return np.sqrt(z)

FT = FunctionTransformer(func = function1)
FT.fit(X)
newdata = FT.transform(X)
newdata

array([[2.        , 1.        , 1.41421356, 1.41421356],
       [1.        , 1.73205081, 3.        , 1.73205081],
       [2.23606798, 2.64575131, 2.23606798, 1.        ]])

## Binarizer

و هي تقوم بتحويل كل الأرقام إلي صفر او واحد , حسب قيمة العتبة 

threshold

In [ ]:
from sklearn.preprocessing import Binarizer
X = [[ 1., -1., -2.],[ 2., 0., -1.], [ 0., 1., -1.]]

transformer = Binarizer(threshold=1.5 ) 
transformer.fit(X)

transformer

transformer.transform(X)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.]])

## PolynomialFeatures

وهي خاصة بعمل فيتشرز جديدة , هي عبارة عن حاصل ضرب الفيتشرز الحالية بطريقة البولونوميال , فلو كانت الدرجة 2 مثلا , و كان لدينا اصلا عمودين فقط اي 2 فيتشرز , فسيعطي لنا علي الترتيب

In [ ]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X = np.arange(6).reshape(3, 2)
print(X)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
# يتم كتابة الدرجة , وهل تحتوي علي قيمة بياس (رقم 1) ام لا

poly = PolynomialFeatures(degree=2 , include_bias = True)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [ ]:
# ولو تم اختيار interaction_only  كقيمة True  سيعرض فقط قيم a  مضروبة في b  و يحذف الاسس للقيم الوحيدة

poly = PolynomialFeatures(interaction_only=True)
poly.fit_transform(X)


array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.]])