<a href="https://colab.research.google.com/github/abohashem95/SKlearn-codes/blob/main/Data_Split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Split

## train_test_split

تقسيم البيانات لتدريب  و اختبار , يتم تحديد النسبة للاختبار , و عبر قيمة random_state   يتم تحديد نظام 
العشوائية

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=44, shuffle =True)

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)

X
list(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

print(X_train)
print("---------------")
print(y_train)
print("---------------")
print(X_test)
print("---------------")
print(y_test)

[[4 5]
 [0 1]
 [6 7]]
---------------
[2, 0, 3]
---------------
[[2 3]
 [8 9]]
---------------
[1, 4]


## KFold

KFold(n_splits=4, random_state=44, shuffle =True)

In [2]:
import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([11, 22, 33, 44])
# يتم عمل اكثر من تجربة للتقسيم يساوي 2 او 3 او 4
#nn = 2
#nn=3
nn=4

kf = KFold(n_splits=nn)
print(kf.get_n_splits(X))
# KFold(n_splits=nn, random_state=None, shuffle=False)

for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print("---------------------")

4
TRAIN: [1 2 3] TEST: [0]
X_train 
 [[3 4]
 [5 6]
 [7 8]]
X_test 
 [[1 2]]
y_train 
 [22 33 44]
y_test 
 [11]
---------------------
TRAIN: [0 2 3] TEST: [1]
X_train 
 [[1 2]
 [5 6]
 [7 8]]
X_test 
 [[3 4]]
y_train 
 [11 33 44]
y_test 
 [22]
---------------------
TRAIN: [0 1 3] TEST: [2]
X_train 
 [[1 2]
 [3 4]
 [7 8]]
X_test 
 [[5 6]]
y_train 
 [11 22 44]
y_test 
 [33]
---------------------
TRAIN: [0 1 2] TEST: [3]
X_train 
 [[1 2]
 [3 4]
 [5 6]]
X_test 
 [[7 8]]
y_train 
 [11 22 33]
y_test 
 [44]
---------------------


## Repeated KFold

و هي تقوم بعمل kfold 

اكثر من مرة, بتنويعات مختلفة

rkf = RepeatedKFold(n_splits=4, n_repeats=4, random_state=44)

In [3]:
import numpy as np
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([11, 22, 33, 44])
# هنا يتم تحديد عدد الاقسام و عدد التكرارات
rkf = RepeatedKFold(n_splits=4, n_repeats=4, random_state=44)
for train_index, test_index in rkf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')

TRAIN: [0 1 2] TEST: [3]
X_train 
 [[1 2]
 [3 4]
 [5 6]]
X_test 
 [[7 8]]
y_train 
 [11 22 33]
y_test 
 [44]
*********************
TRAIN: [0 1 3] TEST: [2]
X_train 
 [[1 2]
 [3 4]
 [7 8]]
X_test 
 [[5 6]]
y_train 
 [11 22 44]
y_test 
 [33]
*********************
TRAIN: [0 2 3] TEST: [1]
X_train 
 [[1 2]
 [5 6]
 [7 8]]
X_test 
 [[3 4]]
y_train 
 [11 33 44]
y_test 
 [22]
*********************
TRAIN: [1 2 3] TEST: [0]
X_train 
 [[3 4]
 [5 6]
 [7 8]]
X_test 
 [[1 2]]
y_train 
 [22 33 44]
y_test 
 [11]
*********************
TRAIN: [0 2 3] TEST: [1]
X_train 
 [[1 2]
 [5 6]
 [7 8]]
X_test 
 [[3 4]]
y_train 
 [11 33 44]
y_test 
 [22]
*********************
TRAIN: [0 1 3] TEST: [2]
X_train 
 [[1 2]
 [3 4]
 [7 8]]
X_test 
 [[5 6]]
y_train 
 [11 22 44]
y_test 
 [33]
*********************
TRAIN: [1 2 3] TEST: [0]
X_train 
 [[3 4]
 [5 6]
 [7 8]]
X_test 
 [[1 2]]
y_train 
 [22 33 44]
y_test 
 [11]
*********************
TRAIN: [0 1 2] TEST: [3]
X_train 
 [[1 2]
 [3 4]
 [5 6]]
X_test 
 [[7 8]]
y_train 


## Stratified KFold

و هي لعمل تقسيم الطبقات بشكل متوازن مع انواع الاصناف

In [4]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([0,0,0,1])
skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(X, y)

print(skf)

for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')
 

StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [2 3] TEST: [0 1]
X_train 
 [[5 6]
 [7 8]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1]
y_test 
 [0 0]
*********************
TRAIN: [0 1] TEST: [2 3]
X_train 
 [[1 2]
 [3 4]]
X_test 
 [[5 6]
 [7 8]]
y_train 
 [0 0]
y_test 
 [0 1]
*********************


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  % (min_groups, self.n_splits)), UserWarning)


## Shuffle Split

يقوم بعمل اختيار عشوائي للتدريب و الاختبار حسب النسبة المعطاة

In [5]:
import numpy as np
from sklearn.model_selection import ShuffleSplit
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [3, 4], [5, 6]])
y = np.array([1, 2, 1, 2, 1, 2])
rs = ShuffleSplit(n_splits=5, test_size=.1, random_state=0)
rs.get_n_splits(X)

print(rs)

for train_index, test_index in rs.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

rs = ShuffleSplit(n_splits=5, train_size=0.5, test_size=.25,random_state=0)
for train_index, test_index in rs.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

ShuffleSplit(n_splits=5, random_state=0, test_size=0.1, train_size=None)
TRAIN: [2 1 3 0 4] TEST: [5]
TRAIN: [3 4 0 2 5] TEST: [1]
TRAIN: [5 1 2 4 0] TEST: [3]
TRAIN: [2 3 4 1 0] TEST: [5]
TRAIN: [4 3 5 1 0] TEST: [2]
TRAIN: [1 3 0] TEST: [5 2]
TRAIN: [4 0 2] TEST: [1 3]
TRAIN: [1 2 4] TEST: [3 5]
TRAIN: [3 4 1] TEST: [5 2]
TRAIN: [3 5 1] TEST: [2 4]


## Stratified Shuffle Split

نفس الفكرة السابقة لكن مع مراعاة توزيع النسب

In [6]:
 import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 0, 1, 1, 1])
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss.get_n_splits(X, y)
print(sss)
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)
TRAIN: [2 5 1 3] TEST: [0 4]
X_train 
 [[1 2]
 [3 4]
 [3 4]
 [3 4]]
X_test 
 [[1 2]
 [1 2]]
y_train 
 [0 1 0 1]
y_test 
 [0 1]
*********************
TRAIN: [0 4 3 1] TEST: [2 5]
X_train 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1 1 0]
y_test 
 [0 1]
*********************
TRAIN: [0 4 3 1] TEST: [2 5]
X_train 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1 1 0]
y_test 
 [0 1]
*********************
TRAIN: [5 4 1 2] TEST: [0 3]
X_train 
 [[3 4]
 [1 2]
 [3 4]
 [1 2]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [1 1 0 0]
y_test 
 [0 1]
*********************
TRAIN: [1 5 2 4] TEST: [0 3]
X_train 
 [[3 4]
 [3 4]
 [1 2]
 [1 2]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1 0 1]
y_test 
 [0 1]
*********************
