<a href="https://colab.research.google.com/github/abohashem95/SKlearn-codes/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## introduction for SimpleImputer

In [ ]:
#import SimpleImputer library and numpy library
from sklearn.impute import SimpleImputer as si
import numpy as np

In [ ]:

X = [[1,2,np.nan,4,5,6,np.nan,8,9,10],[11,12,np.nan,14,15,np.nan,17,18,19,20]]
# Cleaning data
'''
impute.SimpleImputer(missing_values=nan, strategy='mean’, fill_value=None, verbose=0, copy=True)
'''
#make object
ImputedModule = si(missing_values= np.nan,strategy="mean")

#fit and transform
imputedX = ImputedModule.fit(X)
X = ImputedModule.transform(X)


In [ ]:
print(X)

[[ 1.  2.  4.  5.  6. 17.  8.  9. 10.]
 [11. 12. 14. 15.  6. 17. 18. 19. 20.]]


## try simpleimputer in breast cancer

note: it doesn't make seanse because it doesn't contain Nan values

In [ ]:
# Import Libraries
from sklearn.datasets import load_breast_cancer
from sklearn.impute import SimpleImputer
import numpy as np
#----------------------------------------------------

#load breast cancer data
BreastData = load_breast_cancer()

#X Data
X = BreastData.data

#y Data
y = BreastData.target
#----------------------------------------------------
# Cleaning data

'''
impute.SimpleImputer(missing_values=nan, strategy='mean’, fill_value=None, verbose=0, copy=True)
'''
ImputedModule = SimpleImputer(missing_values = np.nan, strategy ='mean')
ImputedX = ImputedModule.fit(X)
X = ImputedX.transform(X)


#X Data
print('X Data is \n' , X[:10])

#y Data
print('y Data is \n' , y[:10])

X Data is 
 [[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e-01 2.8

# try simpleImputer with small data

In [ ]:
# example 1  using mean

import numpy as np

from sklearn.impute import SimpleImputer

data = [[1,2,np.nan],
        [3,np.nan,1],
        [5,np.nan,0],
        [np.nan,4,6 ],
        [5,0,np.nan],
        [4,5,5]]

imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(data)

modifieddata = imp.transform(data)
print(modifieddata)


[[1.   2.   3.  ]
 [3.   2.75 1.  ]
 [5.   2.75 0.  ]
 [3.6  4.   6.  ]
 [5.   0.   3.  ]
 [4.   5.   5.  ]]


In [ ]:
# emample 2 using median

import numpy as np

from sklearn.impute import SimpleImputer

data = [[1,2,np.nan],
        [3,np.nan,1],
        [5,np.nan,0],
        [np.nan,4,6 ],
        [5,0,np.nan],
        [4,5,5]]

imp = SimpleImputer(missing_values=np.nan, strategy='median')
imp = imp.fit(data)

modifieddata = imp.transform(data)
print(modifieddata)

[[1. 2. 3.]
 [3. 3. 1.]
 [5. 3. 0.]
 [4. 4. 6.]
 [5. 0. 3.]
 [4. 5. 5.]]


In [ ]:
# example 3 using mean and zero missing value

from sklearn.impute import SimpleImputer


data = [[1,2,0],
        [3,0,1],
        [5,0,0],
        [0,4,6],
        [5,0,0],
        [4,5,5]]


imp = SimpleImputer(missing_values=0, strategy='mean')
imp = imp.fit(data)


modifieddata = imp.transform(data)
print(modifieddata)

[[1.         2.         4.        ]
 [3.         3.66666667 1.        ]
 [5.         3.66666667 4.        ]
 [3.6        4.         6.        ]
 [5.         3.66666667 4.        ]
 [4.         5.         5.        ]]
