<a href="https://colab.research.google.com/github/abohashem95/SKlearn-codes/blob/main/Metrics_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Metrics Module

 هي بالغة الأهمية في عمل حساب لكمية الأخطاء اثناء الاختبار , وتنقسم إلي نوعين , نوع للتوقع , ونوع للتصنيف  


## Regrassion tools

### mean absolute error 

equation:
1/n * sum(y-y`)

where
y: y true

y`: y predict

n: number of samples

code:

 **Import Libraries**

from sklearn.metrics import mean_absolute_error 

**----------------------------------------------------**

**Calculating Mean Absolute Error**

MAEValue = mean_absolute_error(y_test, y_pred, 
multioutput='uniform_average') 
   **it can be raw_values**

print('Mean Absolute Error Value is : ', MAEValue)




In [ ]:
# example 1 real numbers in list

from sklearn.metrics import mean_absolute_error
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
mean_absolute_error(y_true, y_pred)


0.5

In [ ]:
# example 2  matrices 

y_true = [[0.5, 1], [-1, 1], [7, -6]]
y_pred = [[0, 2], [-1, 2], [8, -5]]
# هنا ياتي بالمتوسط لهم كلهم
print(mean_absolute_error(y_true, y_pred)) # 0.75
print(mean_absolute_error(y_true, y_pred, multioutput='uniform_average')) # 0.75
# و هنا لكل صف علي حدة 
print(mean_absolute_error(y_true, y_pred, multioutput='raw_values')) # array([0.5, 1. ])


0.75
0.75
[0.5 1. ]


### mean squared error 

equation:
1/n * sum(y-y`)^2

where
y: y true

y`: y predict

n: number of samples

code:

 **Import Libraries**

from sklearn.metrics import mean_squared_error  

**----------------------------------------------------**

**Calculating Mean squared Error**

MSEValue = mean_squared_error(y_test, y_pred, multioutput='uniform_average') 
   **it can be raw_values**

print('Mean Squared Error Value is : ', MSEValue)


In [ ]:
# example 1 

from sklearn.metrics import mean_squared_error
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
mean_squared_error(y_true, y_pred)

0.375

In [ ]:
# example 2 

y_true = [[0.5, 1],[-1, 1],[7, -6]]
y_pred = [[0, 2],[-1, 2],[8, -5]]

# هنا ياتي بالمتوسط لهم كلهم

print(mean_squared_error(y_true, y_pred))
print(mean_squared_error(y_true, y_pred, multioutput='uniform_average')) 
# و هنا لكل صف علي حدة 

print(mean_squared_error(y_true, y_pred, multioutput='raw_values'))

0.7083333333333334
0.7083333333333334
[0.41666667 1.        ]


### Median Absolute Error

نفس فكرة mean  لكنه يقوم برص قيم الاخطاء و اختيار القيمة الـmedian



code:

 **Import Libraries**

from sklearn.metrics import median_absolute_error  

**----------------------------------------------------**

**Calculating Median Absolute Error**

MdSEValue = median_absolute_error(y_test, y_pred) 
   
print('Median Squared Error Value is : ', MdSEValue )


In [ ]:
# example 1

from sklearn.metrics import median_absolute_error
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
median_absolute_error(y_true, y_pred)

0.5

## classification tools

### Confusion Matrix



   ==============

      TP     FP

      FN     TN
   ==============

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred = ['a','a','b','b','a','b','a','a','a','a']
y_true  = ['a','b','b','a','b','a','a','b','a','b']
confusion_matrix(y_true, y_pred)




#                pred a      pred b
#   actual a       3           2

#   actual b       4           1




array([[3, 2],
       [4, 1]])

In [ ]:
#example 2

from sklearn.metrics import confusion_matrix
y_pred =  ['a','b','c','a','b','c','a','b','c','a']
y_true =  ['a','a','b','b','a','b','c','c','b','b']
confusion_matrix(y_true, y_pred)


array([[1, 2, 0],
       [2, 0, 3],
       [1, 1, 0]])

In [ ]:
# example 3 

from sklearn.metrics import confusion_matrix
y_pred = [5,8,9,9,8,5,5,9,8,5,9,8]
y_true =  [9,9,8,8,5,5,9,5,8,9,8,5]
confusion_matrix(y_true, y_pred)

array([[1, 2, 1],
       [0, 1, 3],
       [3, 1, 0]])

### Accuracy Score

((TP + TN) / float(TP + TN + FP + FN))

**Import Libraries**

from sklearn.metrics import accuracy_score

**----------------------------------------------------**

**Calculating Accuracy Score  : ((TP + TN) / float(TP + TN + FP + FN))**

AccScore = accuracy_score(y_test, y_pred, normalize=False)

print('Accuracy Score is : ', AccScore)

In [ ]:
# example 1

from sklearn.metrics import accuracy_score
y_pred = [0, 2, 1, 3,5,3]
y_true = [0, 1, 2, 3,5,3]
print(accuracy_score(y_true, y_pred)) # fraction of all Trues over everything
print(accuracy_score(y_true, y_pred, normalize=False)) #number of all Trues

0.6666666666666666
4


### Recall Score (Sensitivity)

(TP / float(TP + FN))   


recall_score(y_true, y_pred, labels=None, pos_label=1, average=’binary’, sample_weight=None)

In [ ]:
# example

from sklearn.metrics import recall_score
y_pred =  ['a','b','c','a','b','c','a','b','c','a']
y_true =   ['a','a','b','b','a','b','c','c','b','b']
recall_score(y_true, y_pred, average=None)

array([0.33333333, 0.        , 0.        ])

### Precision Score (Specificity)

(TP / float(TP + FP)) 

precision_score(y_true, y_pred, labels=None, pos_label=1, average=’binary’,sample_weight=None)

it can be : binary,macro,weighted,samples

In [ ]:
# example 

from sklearn.metrics import precision_score
 
y_pred =  ['a','b','c','a','b','c','a','b','c','a']
y_true =   ['a','a','b','b','a','b','c','c','b','b']

precision_score(y_true, y_pred, average=None)

array([0.25, 0.  , 0.  ])

### F1 Score

F1 = 2 * (precision * recall) / (precision + recall)

f1_score(y_true, y_pred, labels=None, pos_label=1, average=’binary’, sample_weight=None)

it can be : binary,macro,weighted,samples

In [ ]:
# example 

from sklearn.metrics import f1_score
y_pred = [0, 2, 1, 0, 0, 1]
y_true = [0, 1, 2, 0, 1, 2]
f1_score(y_true, y_pred, average='micro')

0.3333333333333333

### Precision Recall Fscore Support

metrics.precision_recall_fscore_support(y_true, y_pred, beta=1.0, labels=None, pos_label=1, average= None, warn_for = ('precision’,’recall’, ’f-score’), sample_weight=None)

it can be : binary,macro,weighted,samples

In [ ]:
# example 

import numpy as np
from sklearn.metrics import precision_recall_fscore_support
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
y_true =  np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
 
precision_recall_fscore_support(y_true, y_pred, average=None)

(array([0.66666667, 0.        , 0.        ]),
 array([1., 0., 0.]),
 array([0.8, 0. , 0. ]),
 array([2, 2, 2]))

### Classification Report

وهي تقوم بحساب كلا من : precision , recall , f1score , support  لكل قيمة من القيم , سواء ارقام او نصوص , كما تقوم بإظهار المتوسطات بأنواعها macro , micro , support





classification_report(y_true, y_pred, labels=None, target_names=None,sample_weight=None, digits=2, output_dict=False)




In [ ]:
# example 
import numpy as np
from sklearn.metrics import precision_recall_fscore_support
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
y_true =  np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
 
precision_recall_fscore_support(y_true, y_pred, average="micro")

(0.3333333333333333, 0.3333333333333333, 0.3333333333333333, None)